## Todo only when running on buster
- name: Add stretch repository
  apt_repository:
    repo: deb http://deb.debian.org/debian stretch main
    state: present
    filename: 'local-stretch'
  when: ansible_distribution != 'Ubuntu'

- name: Add bionic repository
  apt_repository:
    repo: deb http://security.ubuntu.com/ubuntu bionic-security main
    state: present
    filename: 'local-bionic'
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- name: Install packages for luacrypto
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libssl1.0-dev
      - gcc
      - git
      - lua-cjson-dev
      - liblua5.2-dev
      - luarocks

- name: Install libssl1.0-dev
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libssl1.0.2  # avoid libssl1.0.2 from being removed on -dev purge
  when: ansible_distribution != 'Ubuntu'

- name: Build lua luajwtjitsi
  command:
    cmd: luarocks install luajwtjitsi
    creates: /usr/local/lib/luarocks/rocks/luajwtjitsi
  notify:
    - restart prosody

# TODO eewww
- name: Remove locally created lua-cjson, breaks prosody
  file:
    path: /usr/local/lib/lua/5.2/cjson.so
    state: absent

- name: Remove stretch repository
  apt_repository:
    repo: deb http://deb.debian.org/debian stretch main
    state: absent
    filename: 'local-stretch'
  when: ansible_distribution != 'Ubuntu'

- name: Remove bionic repository
  apt_repository:
    repo: deb http://security.ubuntu.com/ubuntu bionic-security main
    state: absent
    filename: 'local-bionic'
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- name: Restore libssl-dev
  apt:
    name: libssl-dev
    state: present

