---
- name: Install Java
  include_role:
    name: common
    tasks_from: java

- name: Add jitsi repo
  include_role:
    name: common
    tasks_from: jitsi_repo

- include: preconfigure_jitsi.yml
  tags:
    - pkginstall

# tune systemd
- include: systemd_tuning.yml

# Get ahead of jitsi-meet-web-config Depends and install nginx
# Also install wget for jitsi's letsencrypt script (case it get used)
- name: Install dependencies
  apt:
    pkg: "{{ packages }}"
    state: present
  vars:
    packages:
      - nginx
      - wget
  tags:
    - pkginstall

# Use Debian's certbot to get a LE cert
# jitsi's script is broken in so many ways...
- import_tasks: tasks/certbot.yml
  when: debian_certbot
  tags:
    - pkginstall

- name: Install Jitsi Meet
  apt:
    pkg: "{{ packages }}"
    state: present
    install_recommends: no  # avoid pulling sturn
  vars:
    packages:
      - jitsi-meet-web
      - jitsi-meet-web-config
      - jicofo
      - jitsi-meet-prosody
  tags:
    - pkginstall

- name: Disable encryption requirement for clients
  lineinfile:
    path: /etc/prosody/prosody.cfg.lua
    regexp: 'c2s_require_encryption = '
    line: 'c2s_require_encryption = false '
  notify:
   - restart prosody

## TODO Since components are being deprecated in favour of MUCs
## This should probably go away
- name: Listen on all ifaces
  lineinfile:
    path: /etc/prosody/prosody.cfg.lua
    regexp: 'component_interface = '
    insertafter: 'certificates = "certs"'
    line: 'component_interface = { "*" }'
  notify:
   - restart prosody

## LDAP
- import_tasks: tasks/ldap.yml
  when: xmpp_auth == "ldap"
  tags:
    - authconf

## Token
- import_tasks: tasks/token.yml
  when: xmpp_auth == "token"
  tags:
    - authconf

- name: Add presence_idendity when storing participants metadata in recordings
  file:
    state: link
    src: /usr/share/jitsi-meet/prosody-plugins/mod_presence_identity.lua
    dest: /usr/lib/prosody/modules/mod_presence_identity.lua
    owner: root
    group: root
  notify:
   - restart prosody
  tags:
    - prosodyconf

- name: Prosody domain conf
  template:
    src: prosody_domain.cfg.lua
    dest: /etc/prosody/conf.avail/{{ meet_domain }}.cfg.lua
    owner: root
    group: root
    mode: 0644
  notify:
   - restart prosody
  tags:
    - prosodyconf
    - authconf

- name: Jitsi Meet client config
  template:
    src: jitsimeet-config.js
    dest: /etc/jitsi/meet/{{ meet_domain }}-config.js
    owner: root
    group: root
    mode: 0644
  tags:
    - meetconf
    - authconf

- name: Jicofo config I
  template:
    src: jicofo_config
    dest: /etc/jitsi/jicofo/config
    owner: jicofo
    group: jitsi
    mode: 0644
  notify:
   - restart jicofo
  tags:
    - jicofoconf

- name: Jicofo config II
  template:
    src: jicofo_sip-communicator.properties
    dest: /etc/jitsi/jicofo/sip-communicator.properties
    owner: jicofo
    group: jitsi
    mode: 0600
  notify:
   - restart jicofo
  tags:
    - jicofoconf
    - authconf

- name: Jicofo config III
  template:
    src: jicofo.conf
    dest: /etc/jitsi/jicofo/jicofo.conf
    owner: jicofo
    group: jitsi
    mode: 0644
  notify:
   - restart jicofo
  tags:
    - jicofoconf

- name: Nginx virtualhost config
  template:
    src: nginx.conf
    dest: /etc/nginx/sites-available/{{ meet_domain}}.conf
    owner: root
    group: root
    mode: 0644
  notify:
   - reload nginx
  tags:
    - nginxconf

- name: Enable nginx virtualhost
  file:
    state: link
    src: /etc/nginx/sites-available/{{ meet_domain}}.conf
    dest: /etc/nginx/sites-enabled/{{ meet_domain}}.conf
    owner: root
    group: root
  notify:
   - reload nginx
  tags:
    - nginxconf

- include: xmpp_users.yml
  tags:
    - xmppusers
